name: CI/CD Pipeline - SMTP Email Notification

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          python -m pip install flake8 pytest pytest-cov

      - name: Lint code
        run: |
          flake8 --count --select=E901,E999,F821,F822,F823 --show-source --statistics CICD_Tests/160724/test_script.py
          flake8 CICD_Tests/160724/test_script.py

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'

      - name: Run tests
        run: |
          python CICD_Tests/160724/test_script.py

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage.xml  # Adjust based on your coverage report file

  notify:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Send notification email
        env:
          SMTP_SERVER: smtp.gmail.com
          SMTP_PORT: 587
          SMTP_USERNAME: ${{ secrets.GMAIL_APP_USERNAME }}  # Replace with your Gmail address
          SMTP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}  # Generate an App Password for Gmail and store it as a secret
          TO_EMAIL: evgenyb@egged.co.il  # Replace with recipient's email
          FROM_EMAIL: zalupatest@gmail.com  # Replace with sender's email
        run: |
          echo "To: $TO_EMAIL" > email.txt
          echo "From: $FROM_EMAIL" >> email.txt
          echo "Subject: CI/CD Pipeline Notification" >> email.txt
          echo "" >> email.txt  # Empty line to separate headers from body
          echo "Your pull request build passed successfully." >> email.txt
          echo "" >> email.txt  # Empty line for proper formatting
          echo "Best regards," >> email.txt
          echo "Your CI/CD Pipeline" >> email.txt
          sendemail -f $FROM_EMAIL -t $TO_EMAIL -u "CI/CD Pipeline Notification" -m "$(cat email.txt)" -s $SMTP_SERVER:$SMTP_PORT -xu $SMTP_USERNAME -xp $SMTP_PASSWORD -o tls=yes
