name: CI/CD Pipeline - Advanced Task 160724

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          python -m pip install flake8 pytest pytest-cov

      - name: Lint code
        run: |
          flake8 --count --select=E901,E999,F821,F822,F823 --show-source --statistics CICD_Tests/160724/test_script.py
          flake8 CICD_Tests/160724/test_script.py
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'

      - name: Run tests
        run: |
          pytest CICD_Tests/160724/test_script.py

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage.xml  # Adjust based on your coverage report file

  notify:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Send notification email
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          TO_EMAIL: evgenyb902@gmail.com  # Replace with recipient's email
        run: |
          echo "Subject: CI/CD Pipeline Notification" > email.txt
          echo "Your pull request build passed successfully." >> email.txt
          sendmail -t < email.txt