name: CI/CD Pipeline - Advanced Task 160724

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'  # Replace with your Python version

      - name: Install dependencies
        run: |
          python -m pip install flake8 pytest pytest-cov

      - name: Lint code
        run: |
          flake8 --count --select=E901,E999,F821,F822,F823 --show-source --statistics CICD_Tests/160724/test_script.py
          flake8 CICD_Tests/160724/test_script.py

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'

      - name: Run tests
        run: |
          python CICD_Tests/160724/test_script.py

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage.xml  # Adjust based on your coverage report file

  notify:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: CINotify Email
        uses: cinotify/github-action@v1.6.0
        with:
          to: "evgenyb902@gmail.com"
          subject: "CI/CD Pipeline Notification"
          body: "<em>This is a notification from GitHub actions.</em>"
          type: "text/html"
