name: Verify Push and Run Python Command

on:
  push:
    branches:
      - main  # Adjust branch name if needed

jobs:
  verify_and_run:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'  # Specify your Python version here

      - name: Install dependencies
        run: |
          python -m pip install pytest  # Installed pytest for testing purposes

      - name: Run Python command
        run: python /github/workspace/CICD_Tests/160724/test_script.py  # Replace with your Python command/script path
