name: Verify Push and Run Python Command

on:
  push:
    branches:
      - main  # Adjust branch name if needed

jobs:
  verify_and_run:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'  # Specify your Python version here

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # If you have any dependencies

      - name: Check if test_script.py exists
        run: |
          if [ -f "test_script.py" ]; then
            echo "test_script.py found."
            export SCRIPT_PATH=$(realpath test_script.py)
            echo "Script path: $SCRIPT_PATH"
          else
            echo "test_script.py not found. Exiting."
            exit 1
          fi

      - name: Run Python command
        run: |
          if [ -f "test_script.py" ]; then
            python $SCRIPT_PATH
          else
            echo "test_script.py not found. Cannot run Python command."
            exit 1
          fi
