name: Verify Push and Run Python Command

on:
  push:
    branches:
      - main  # Adjust branch name if needed

jobs:
  verify_and_run:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'  # Specify your Python version here

      - name: Install dependencies
        run: |
          python -m pip install pytest  # Installed pytest for testing purposes

      - name: Define path to test_script.py
        id: script_path
        run: echo "::set-output name=script_path::$(realpath test_script.py)"

      - name: Show script path
        run: echo "Script path: ${{ steps.script_path.outputs.script_path }}"

      - name: Run Python command
        run: |
          if [ -f "${{ steps.script_path.outputs.script_path }}" ]; then
            python ${{ steps.script_path.outputs.script_path }}
          else
            echo "Script path not defined or file does not exist."
            exit 1
          fi
